-- YouLai_Admin 数据库 (PostgreSQL 16+)
-- Copyright (c) 2021-present, youlai.tech

-- ----------------------------
-- 1. 创建数据库
-- ----------------------------
CREATE DATABASE youlai_admin WITH ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

-- 请切换到 youlai_admin 数据库后再执行后续语句

-- ----------------------------
-- 2. 创建表 && 数据初始化
-- ----------------------------

-- ----------------------------
-- 表结构：sys_dept
-- ----------------------------
DROP TABLE IF EXISTS sys_dept;
CREATE TABLE sys_dept (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    code varchar(100) NOT NULL,
    parent_id bigint DEFAULT 0,
    tree_path varchar(255) NOT NULL,
    sort smallint DEFAULT 0,
    status smallint DEFAULT 1,
    create_by bigint NULL,
    create_time timestamp NULL,
    update_by bigint NULL,
    update_time timestamp NULL,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_dept IS '部门管理表';
COMMENT ON COLUMN sys_dept.id IS '主键';
COMMENT ON COLUMN sys_dept.name IS '部门名称';
COMMENT ON COLUMN sys_dept.code IS '部门编号';
COMMENT ON COLUMN sys_dept.parent_id IS '父节点id';
COMMENT ON COLUMN sys_dept.tree_path IS '父节点id路径';
COMMENT ON COLUMN sys_dept.sort IS '显示顺序';
COMMENT ON COLUMN sys_dept.status IS '状态(1-正常 0-禁用)';
COMMENT ON COLUMN sys_dept.create_by IS '创建人ID';
COMMENT ON COLUMN sys_dept.create_time IS '创建时间';
COMMENT ON COLUMN sys_dept.update_by IS '修改人ID';
COMMENT ON COLUMN sys_dept.update_time IS '更新时间';
COMMENT ON COLUMN sys_dept.is_deleted IS '逻辑删除标识(1-已删除 0-未删除)';
CREATE UNIQUE INDEX uk_code ON sys_dept (code);

-- ----------------------------
-- 表数据：sys_dept
-- ----------------------------
INSERT INTO sys_dept VALUES (1, '有来技术', 'YOULAI', 0, '0', 1, 1, 1, NULL, 1, now(), 0);
INSERT INTO sys_dept VALUES (2, '研发部门', 'RD001', 1, '0,1', 1, 1, 2, NULL, 2, now(), 0);
INSERT INTO sys_dept VALUES (3, '测试部门', 'QA001', 1, '0,1', 1, 1, 2, NULL, 2, now(), 0);

-- ----------------------------
-- 表结构：sys_dict
-- ----------------------------
DROP TABLE IF EXISTS sys_dict;
CREATE TABLE sys_dict (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dict_code varchar(50),
    name varchar(50),
    status smallint DEFAULT 0,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_dict IS '字典表';
COMMENT ON COLUMN sys_dict.id IS '主键';
COMMENT ON COLUMN sys_dict.dict_code IS '字典编码';
COMMENT ON COLUMN sys_dict.name IS '字典名称';
COMMENT ON COLUMN sys_dict.status IS '状态(1-启用 0-停用)';
COMMENT ON COLUMN sys_dict.remark IS '备注';
COMMENT ON COLUMN sys_dict.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict.create_by IS '创建人ID';
COMMENT ON COLUMN sys_dict.update_time IS '更新时间';
COMMENT ON COLUMN sys_dict.update_by IS '修改人ID';
COMMENT ON COLUMN sys_dict.is_deleted IS '逻辑删除(1-已删除 0-未删除)';
CREATE INDEX idx_dict_code ON sys_dict (dict_code);
-- ----------------------------
-- 表数据：sys_dict
-- ----------------------------
INSERT INTO sys_dict VALUES (1, 'gender', '性别', 1, NULL, now(), 1, now(), 1, 0);
INSERT INTO sys_dict VALUES (2, 'notice_type', '通知类型', 1, NULL, now(), 1, now(), 1, 0);
INSERT INTO sys_dict VALUES (3, 'notice_level', '通知级别', 1, NULL, now(), 1, now(), 1, 0);

-- ----------------------------
-- 表结构：sys_dict_item
-- ----------------------------
DROP TABLE IF EXISTS sys_dict_item;
CREATE TABLE sys_dict_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dict_code varchar(50),
    value varchar(50),
    label varchar(100),
    tag_type varchar(50),
    status smallint DEFAULT 0,
    sort int DEFAULT 0,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_dict_item IS '字典项表';
COMMENT ON COLUMN sys_dict_item.id IS '主键';
COMMENT ON COLUMN sys_dict_item.dict_code IS '字典编码，与 sys_dict.dict_code 对应';
COMMENT ON COLUMN sys_dict_item.value IS '字典项值';
COMMENT ON COLUMN sys_dict_item.label IS '字典项标签';
COMMENT ON COLUMN sys_dict_item.tag_type IS '标签样式(primary-主要 success-成功 warning-警告 danger-危险 info-信息，空为无样式)';
COMMENT ON COLUMN sys_dict_item.status IS '状态(1-启用 0-停用)';
COMMENT ON COLUMN sys_dict_item.sort IS '排序';
COMMENT ON COLUMN sys_dict_item.remark IS '备注';
COMMENT ON COLUMN sys_dict_item.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict_item.create_by IS '创建人ID';
COMMENT ON COLUMN sys_dict_item.update_time IS '更新时间';
COMMENT ON COLUMN sys_dict_item.update_by IS '修改人ID';
COMMENT ON COLUMN sys_dict_item.is_deleted IS '逻辑删除(1-已删除 0-未删除)';
CREATE INDEX idx_dict_item_code ON sys_dict_item (dict_code);

-- ----------------------------
-- 表数据：sys_dict_item
-- ----------------------------
INSERT INTO sys_dict_item VALUES (1, 'gender', '1', '男', 'primary', 1, 1, NULL, now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (2, 'gender', '2', '女', 'danger', 1, 2, NULL, now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (3, 'gender', '0', '保密', 'info', 1, 3, NULL, now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (4, 'notice_type', '1', '系统升级', 'success', 1, 1, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (5, 'notice_type', '2', '系统维护', 'primary', 1, 2, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (6, 'notice_type', '3', '安全警告', 'danger', 1, 3, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (7, 'notice_type', '4', '假期通知', 'success', 1, 4, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (8, 'notice_type', '5', '公司新闻', 'primary', 1, 5, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (9, 'notice_type', '99', '其他', 'info', 1, 99, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (10, 'notice_level', 'L', '低', 'info', 1, 1, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (11, 'notice_level', 'M', '中', 'warning', 1, 2, '', now(), 1, now(), 1, 0);
INSERT INTO sys_dict_item VALUES (12, 'notice_level', 'H', '高', 'danger', 1, 3, '', now(), 1, now(), 1, 0);

-- ----------------------------
-- 表结构：sys_menu
-- ----------------------------
DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint NOT NULL,
    tree_path varchar(255),
    name varchar(64) NOT NULL,
    type char(1) NOT NULL,
    route_name varchar(255),
    route_path varchar(128),
    component varchar(128),
    perm varchar(128),
    external_url varchar(512) NULL,
    keep_alive smallint DEFAULT 0,
    visible smallint DEFAULT 1,
    sort int DEFAULT 0,
    icon varchar(64),
    redirect varchar(128),
    create_time timestamp NULL,
    update_time timestamp NULL,
    params jsonb NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_menu IS '系统菜单表';
COMMENT ON COLUMN sys_menu.id IS 'ID';
COMMENT ON COLUMN sys_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN sys_menu.tree_path IS '父节点ID路径';
COMMENT ON COLUMN sys_menu.name IS '菜单名称';
COMMENT ON COLUMN sys_menu.type IS '菜单类型（C-目录 M-菜单 E-外链 B-按钮）';
COMMENT ON COLUMN sys_menu.route_name IS '路由名称（Vue Router 中用于命名路由）';
COMMENT ON COLUMN sys_menu.route_path IS '路由路径（Vue Router 中定义的 URL 路径）';
COMMENT ON COLUMN sys_menu.component IS '组件路径（组件页面完整路径，相对于 src/views/，缺省后缀 .vue）';
COMMENT ON COLUMN sys_menu.external_url IS '外链地址';
COMMENT ON COLUMN sys_menu.perm IS '【按钮】权限标识';
COMMENT ON COLUMN sys_menu.keep_alive IS '【菜单】是否开启页面缓存（1-是 0-否）';
COMMENT ON COLUMN sys_menu.visible IS '显示状态（1-显示 0-隐藏）';
COMMENT ON COLUMN sys_menu.sort IS '排序';
COMMENT ON COLUMN sys_menu.icon IS '菜单图标';
COMMENT ON COLUMN sys_menu.redirect IS '跳转路径';
COMMENT ON COLUMN sys_menu.create_time IS '创建时间';
COMMENT ON COLUMN sys_menu.update_time IS '更新时间';
COMMENT ON COLUMN sys_menu.params IS '路由参数';

-- ----------------------------
-- 表数据：sys_menu
-- ----------------------------
-- 扩展段 8-99 由 sql/extensions/ 脚本占用：动态表单(8,dynamic-form.sql)/工作流(9,workflow.sql)，新扩展模块从 10 领号顺延
-- ID 规则：子 ID = 父 ID × 100 + 两位序号（如 10101 即用户管理 101 的第 1 个按钮），tree_path 与 ID 同构可机器校验
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (1, 0, '0', '系统管理', 'C', '', '/system', 'Layout', NULL, NULL, 1, 1, 'system', '/system/user', now(), now(), NULL);
-- 数据大屏走站内外链：E 型新标签页模式，external_url 填站内路径（前端按当前站点补全域名），指向布局外的独立全屏页
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, external_url, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (2, 0, '0', '数据大屏', 'E', NULL, NULL, NULL, '/data-screen', NULL, NULL, 1, 2, 'el-icon-Monitor', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (3, 0, '0', '代码生成', 'M', 'Codegen', '/codegen', 'codegen/index', NULL, 1, 1, 3, 'code', NULL, now(), now(), NULL);

-- 系统管理
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (101, 1, '0,1', '用户管理', 'M', 'User', 'user', 'system/user/index', NULL, 1, 1, 1, 'el-icon-User', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10101, 101, '0,1,101', '用户查询', 'B', NULL, '', NULL, 'sys:user:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10102, 101, '0,1,101', '用户新增', 'B', NULL, '', NULL, 'sys:user:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10103, 101, '0,1,101', '用户编辑', 'B', NULL, '', NULL, 'sys:user:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10104, 101, '0,1,101', '用户删除', 'B', NULL, '', NULL, 'sys:user:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10105, 101, '0,1,101', '重置密码', 'B', NULL, '', NULL, 'sys:user:reset-password', NULL, 1, 5, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10106, 101, '0,1,101', '用户导入', 'B', NULL, '', NULL, 'sys:user:import', NULL, 1, 6, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10107, 101, '0,1,101', '用户导出', 'B', NULL, '', NULL, 'sys:user:export', NULL, 1, 7, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (102, 1, '0,1', '角色管理', 'M', 'Role', 'role', 'system/role/index', NULL, 1, 1, 2, 'role', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10201, 102, '0,1,102', '角色查询', 'B', NULL, '', NULL, 'sys:role:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10202, 102, '0,1,102', '角色新增', 'B', NULL, '', NULL, 'sys:role:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10203, 102, '0,1,102', '角色编辑', 'B', NULL, '', NULL, 'sys:role:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10204, 102, '0,1,102', '角色删除', 'B', NULL, '', NULL, 'sys:role:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10205, 102, '0,1,102', '角色分配权限', 'B', NULL, '', NULL, 'sys:role:assign', NULL, 1, 5, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (103, 1, '0,1', '菜单管理', 'M', 'SysMenu', 'menu', 'system/menu/index', NULL, 1, 1, 3, 'menu', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10301, 103, '0,1,103', '菜单查询', 'B', NULL, '', NULL, 'sys:menu:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10302, 103, '0,1,103', '菜单新增', 'B', NULL, '', NULL, 'sys:menu:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10303, 103, '0,1,103', '菜单编辑', 'B', NULL, '', NULL, 'sys:menu:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10304, 103, '0,1,103', '菜单删除', 'B', NULL, '', NULL, 'sys:menu:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (104, 1, '0,1', '部门管理', 'M', 'Dept', 'dept', 'system/dept/index', NULL, 1, 1, 4, 'tree', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10401, 104, '0,1,104', '部门查询', 'B', NULL, '', NULL, 'sys:dept:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10402, 104, '0,1,104', '部门新增', 'B', NULL, '', NULL, 'sys:dept:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10403, 104, '0,1,104', '部门编辑', 'B', NULL, '', NULL, 'sys:dept:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10404, 104, '0,1,104', '部门删除', 'B', NULL, '', NULL, 'sys:dept:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (105, 1, '0,1', '字典管理', 'M', 'Dict', 'dict', 'system/dict/index', NULL, 1, 1, 5, 'dict', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10501, 105, '0,1,105', '字典查询', 'B', NULL, '', NULL, 'sys:dict:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10502, 105, '0,1,105', '字典新增', 'B', NULL, '', NULL, 'sys:dict:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10503, 105, '0,1,105', '字典编辑', 'B', NULL, '', NULL, 'sys:dict:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10504, 105, '0,1,105', '字典删除', 'B', NULL, '', NULL, 'sys:dict:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);
-- 字典项已并入字典管理页（左右分栏同屏），不设独立菜单，仅保留按钮权限
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10505, 105, '0,1,105', '字典项查询', 'B', NULL, '', NULL, 'sys:dict-item:list', NULL, 1, 5, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10506, 105, '0,1,105', '字典项新增', 'B', NULL, '', NULL, 'sys:dict-item:create', NULL, 1, 6, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10507, 105, '0,1,105', '字典项编辑', 'B', NULL, '', NULL, 'sys:dict-item:update', NULL, 1, 7, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10508, 105, '0,1,105', '字典项删除', 'B', NULL, '', NULL, 'sys:dict-item:delete', NULL, 1, 8, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (107, 1, '0,1', '系统日志', 'M', 'Log', 'log', 'system/log/index', NULL, 1, 1, 7, 'document', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10701, 107, '0,1,107', '日志查询', 'B', NULL, '', NULL, 'sys:log:list', NULL, 1, 1, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (108, 1, '0,1', '系统配置', 'M', 'Config', 'config', 'system/config/index', NULL, 1, 1, 8, 'setting', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10801, 108, '0,1,108', '系统配置查询', 'B', NULL, '', NULL, 'sys:config:list', 1, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10802, 108, '0,1,108', '系统配置新增', 'B', NULL, '', NULL, 'sys:config:create', 1, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10803, 108, '0,1,108', '系统配置修改', 'B', NULL, '', NULL, 'sys:config:update', 1, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10804, 108, '0,1,108', '系统配置删除', 'B', NULL, '', NULL, 'sys:config:delete', 1, 1, 4, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10805, 108, '0,1,108', '系统配置刷新', 'B', NULL, '', NULL, 'sys:config:refresh', 1, 1, 5, '', NULL, now(), now(), NULL);

INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (109, 1, '0,1', '通知公告', 'M', 'Notice', 'notice', 'system/notice/index', NULL, NULL, 1, 9, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10901, 109, '0,1,109', '通知查询', 'B', NULL, '', NULL, 'sys:notice:list', NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10902, 109, '0,1,109', '通知新增', 'B', NULL, '', NULL, 'sys:notice:create', NULL, 1, 2, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10903, 109, '0,1,109', '通知编辑', 'B', NULL, '', NULL, 'sys:notice:update', NULL, 1, 3, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10904, 109, '0,1,109', '通知删除', 'B', NULL, '', NULL, 'sys:notice:delete', NULL, 1, 4, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10905, 109, '0,1,109', '通知发布', 'B', NULL, '', NULL, 'sys:notice:publish', 1, 1, 5, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (10906, 109, '0,1,109', '通知撤回', 'B', NULL, '', NULL, 'sys:notice:revoke', 1, 1, 6, '', NULL, now(), now(), NULL);

-- 实战文档双形态置顶（内嵌 iframe + 外链新标签），直观演示系统对两种外链打开方式的支持

-- ============================ 通用组件（顶级 ID=4） ============================
-- 前端模板招牌能力聚合，独立顶级便于访客沉淀组件库；按用途三分组：基础/表单/表格
-- 物理目录 views/demo/component（基础与表单）与 views/demo/table（表格）一一对应
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (4, 0, '0', '通用组件', 'C', '', '/component', 'Layout', NULL, NULL, 1, 4, 'el-icon-SetUp', '/component/basic/icon-demo', now(), now(), NULL);

-- 基础组件（不依附表单/表格场景的通用 UI 能力）
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (401, 4, '0,4', '基础组件', 'C', '', 'basic', 'Layout', NULL, NULL, 1, 1, 'el-icon-Brush', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40101, 401, '0,4,401', 'Icons', 'M', 'IconDemo', 'icon-demo', 'demo/component/icons', NULL, 1, 1, 1, 'el-icon-Notification', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40102, 401, '0,4,401', '拖拽组件', 'M', 'Drag', 'drag', 'demo/component/drag', NULL, NULL, 1, 2, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40103, 401, '0,4,401', '滚动文本', 'M', 'TextScroll', 'text-scroll', 'demo/component/text-scroll', NULL, NULL, 1, 3, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40104, 401, '0,4,401', '字典实时同步', 'M', 'DictSync', 'dict-sync', 'demo/component/dict-sync', NULL, NULL, 1, 4, '', '', now(), now(), NULL);

-- 表单组件（数据录入场景）
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (402, 4, '0,4', '表单组件', 'C', '', 'form', 'Layout', NULL, NULL, 1, 2, 'el-icon-EditPen', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40201, 402, '0,4,402', '富文本编辑器', 'M', 'WangEditor', 'wang-editor', 'demo/component/wang-editor', NULL, 1, 1, 1, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40202, 402, '0,4,402', '图片上传', 'M', 'Upload', 'upload', 'demo/component/upload', NULL, 1, 1, 2, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40203, 402, '0,4,402', '图标选择器', 'M', 'DemoIconSelect', 'icon-select', 'demo/component/icon-select', NULL, 1, 1, 3, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40204, 402, '0,4,402', '字典组件', 'M', 'DictDemo', 'dict-demo', 'demo/component/dictionary', NULL, 1, 1, 4, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40205, 402, '0,4,402', '列表选择器', 'M', 'TableSelect', 'table-select', 'demo/component/table-select/index', NULL, 1, 1, 5, '', '', now(), now(), NULL);

-- 表格组件（数据展示场景，物理目录 views/demo/table 与之对应）
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (403, 4, '0,4', '表格组件', 'C', '', 'table', 'Layout', NULL, NULL, 1, 3, 'el-icon-Grid', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40301, 403, '0,4,403', '增删改查', 'M', 'Crud', 'crud', 'demo/table/crud/index', NULL, 1, 1, 1, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40302, 403, '0,4,403', 'CRUD单文件', 'M', 'CrudSingle', 'crud-single', 'demo/table/crud-single', NULL, 1, 1, 2, 'el-icon-Reading', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40303, 403, '0,4,403', 'VxeTable', 'M', 'VxeTable', 'vxe-table', 'demo/table/vxe-table/index', NULL, 1, 1, 3, 'el-icon-MagicStick', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (40304, 403, '0,4,403', '自适应表格操作列', 'M', 'AutoOperationColumn', 'operation-column', 'demo/table/auto-operation-column', NULL, 1, 1, 4, '', '', now(), now(), NULL);

-- ============================ 多级菜单（顶级 ID=5） ============================
-- 独立顶级，直观演示菜单驱动动态路由的嵌套能力，避免折叠导致顶级菜单不可见
-- 物理目录 views/demo/route/multi-level 与之对应
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (5, 0, '0', '多级菜单', 'C', '', '/multi-level', 'Layout', NULL, NULL, 1, 5, 'el-icon-Guide', '/multi-level/level-one/level-two/level-three-a', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (501, 5, '0,5', '一级菜单', 'C', '', 'level-one', 'Layout', NULL, NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (50101, 501, '0,5,501', '二级菜单', 'C', '', 'level-two', 'Layout', NULL, NULL, 1, 1, '', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (5010101, 50101, '0,5,501,50101', '三级菜单 A', 'M', 'MultiLevelLevelThreeA', 'level-three-a', 'demo/route/multi-level/level-one/level-two/level-three-a/index', NULL, 1, 1, 1, '', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (5010102, 50101, '0,5,501,50101', '三级菜单 B', 'M', 'MultiLevelLevelThreeB', 'level-three-b', 'demo/route/multi-level/level-one/level-two/level-three-b/index', NULL, 1, 1, 2, '', '', now(), now(), NULL);

-- ============================ 路由示例（顶级 ID=6） ============================
-- 路由层能力演示：传参（页内切换）、页面缓存、页面跳转、内嵌页面（iframe）、外部链接（E 型新标签）
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (6, 0, '0', '路由示例', 'C', '', '/route-example', 'Layout', NULL, NULL, 1, 6, 'el-icon-Share', '/route-example/route-param', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (601, 6, '0,6', '路由参数', 'M', 'RouteParam', 'route-param', 'demo/route/route-param', NULL, 1, 1, 1, 'el-icon-Star', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (602, 6, '0,6', '页面缓存', 'M', 'RouteCache', 'cache', 'demo/route/cache/index', NULL, 1, 1, 2, 'el-icon-Stopwatch', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (603, 6, '0,6', '页面跳转', 'M', 'RouteNavigate', 'navigate', 'demo/route/navigate/index', NULL, 1, 1, 3, 'el-icon-Position', NULL, now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, external_url, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (604, 6, '0,6', '内嵌页面', 'E', 'PracticeDoc', 'iframe', 'iframe', 'https://www.apifox.cn/apidoc/shared-195e783f-4d85-4235-a038-eec696de4ea5', NULL, 1, 1, 4, 'el-icon-Document', '', now(), now(), NULL);
INSERT INTO sys_menu (id, parent_id, tree_path, name, type, route_name, route_path, component, external_url, perm, keep_alive, visible, sort, icon, redirect, create_time, update_time, params) VALUES (605, 6, '0,6', '外部链接', 'E', NULL, NULL, NULL, 'https://juejin.cn/post/7228990409909108793', NULL, NULL, 1, 5, 'el-icon-Link', '', now(), now(), NULL);


-- ----------------------------
-- 表结构：sys_role
-- ----------------------------
DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(64) NOT NULL,
    code varchar(32) NOT NULL,
    sort int NULL,
    status smallint DEFAULT 1,
    data_scope smallint NULL,
    create_by bigint NULL,
    create_time timestamp NULL,
    update_by bigint NULL,
    update_time timestamp NULL,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_role IS '系统角色表';
COMMENT ON COLUMN sys_role.name IS '角色名称';
COMMENT ON COLUMN sys_role.code IS '角色编码';
COMMENT ON COLUMN sys_role.sort IS '显示顺序';
COMMENT ON COLUMN sys_role.status IS '角色状态(1-正常 0-停用)';
COMMENT ON COLUMN sys_role.data_scope IS '数据权限(1-所有数据 2-部门及子部门数据 3-本部门数据 4-本人数据 5-自定义部门数据)';
COMMENT ON COLUMN sys_role.create_by IS '创建人 ID';
COMMENT ON COLUMN sys_role.create_time IS '创建时间';
COMMENT ON COLUMN sys_role.update_by IS '更新人ID';
COMMENT ON COLUMN sys_role.update_time IS '更新时间';
COMMENT ON COLUMN sys_role.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';
CREATE UNIQUE INDEX uk_name ON sys_role (name);
CREATE UNIQUE INDEX uk_role_code ON sys_role (code);

-- ----------------------------
-- 表数据：sys_role
-- ----------------------------
INSERT INTO sys_role VALUES (1, '超级管理员', 'ROOT', 1, 1, 1, NULL, now(), NULL, now(), 0);
INSERT INTO sys_role VALUES (2, '系统管理员', 'ADMIN', 2, 1, 1, NULL, now(), NULL, NULL, 0);
INSERT INTO sys_role VALUES (3, '访问游客', 'GUEST', 3, 1, 3, NULL, now(), NULL, now(), 0);
INSERT INTO sys_role VALUES (4, '部门主管', 'DEPT_MANAGER', 4, 1, 2, NULL, now(), NULL, now(), 0);
INSERT INTO sys_role VALUES (5, '部门成员', 'DEPT_MEMBER', 5, 1, 3, NULL, now(), NULL, now(), 0);
INSERT INTO sys_role VALUES (6, '普通员工', 'EMPLOYEE', 6, 1, 4, NULL, now(), NULL, now(), 0);
INSERT INTO sys_role VALUES (7, '自定义权限用户', 'CUSTOM_USER', 7, 1, 5, NULL, now(), NULL, now(), 0);

-- ----------------------------
-- 表结构：sys_role_menu
-- ----------------------------
DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL
);
COMMENT ON TABLE sys_role_menu IS '角色菜单关联表';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单ID';
CREATE UNIQUE INDEX uk_roleid_menuid ON sys_role_menu (role_id, menu_id);

-- ----------------------------
-- 表结构：sys_role_dept
-- ----------------------------
DROP TABLE IF EXISTS sys_role_dept;
CREATE TABLE sys_role_dept (
    role_id bigint NOT NULL,
    dept_id bigint NOT NULL
);
COMMENT ON TABLE sys_role_dept IS '角色部门关联表';
COMMENT ON COLUMN sys_role_dept.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_dept.dept_id IS '部门ID';
CREATE UNIQUE INDEX uk_roleid_deptid ON sys_role_dept (role_id, dept_id);

-- ----------------------------
-- 表数据：sys_role_dept
-- ----------------------------
INSERT INTO sys_role_dept VALUES (7, 1) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_dept VALUES (7, 2) ON CONFLICT DO NOTHING;

-- ============================================
-- 系统管理员角色菜单权限（role_id=2，基础段顶级 1-6 全量）
INSERT INTO sys_role_menu VALUES
(2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 101), (2, 10101), (2, 10102),
(2, 10103), (2, 10104), (2, 10105), (2, 10106), (2, 10107), (2, 102), (2, 10201), (2, 10202), (2, 10203), (2, 10204),
(2, 10205), (2, 103), (2, 10301), (2, 10302), (2, 10303), (2, 10304), (2, 104), (2, 10401), (2, 10402), (2, 10403),
(2, 10404), (2, 105), (2, 10501), (2, 10502), (2, 10503), (2, 10504), (2, 10505), (2, 10506), (2, 10507), (2, 10508),
(2, 107), (2, 10701), (2, 108), (2, 10801), (2, 10802), (2, 10803), (2, 10804), (2, 10805), (2, 109), (2, 10901),
(2, 10902), (2, 10903), (2, 10904), (2, 10905), (2, 10906), (4, 1), (4, 101), (4, 10101), (4, 10102), (4, 10103),
(4, 10104), (4, 10105), (4, 10106), (4, 10107), (4, 102), (4, 10201), (4, 10202), (4, 10203), (4, 10204), (4, 10205),
(5, 1), (5, 101), (5, 10101), (5, 10102), (5, 10103), (5, 10104), (5, 10105), (5, 10106), (5, 10107), (5, 102),
(5, 10201), (5, 10202), (5, 10203), (5, 10204), (5, 10205), (6, 1), (6, 101), (6, 10101), (6, 10102), (6, 10103),
(6, 10104), (6, 10105), (6, 10106), (6, 10107), (6, 102), (6, 10201), (6, 10202), (6, 10203), (6, 10204), (6, 10205),
(7, 1), (7, 101), (7, 10101), (7, 10102), (7, 10103), (7, 10104), (7, 10105), (7, 10106), (7, 10107), (7, 102),
(7, 10201), (7, 10202), (7, 10203), (7, 10204), (7, 10205), (2, 401), (2, 40101), (2, 40102), (2, 40103), (2, 40104), (2, 402), (2, 40201),
(2, 40202), (2, 40203), (2, 40204), (2, 40205), (2, 403), (2, 40301), (2, 40302), (2, 40303), (2, 40304), (2, 501),
(2, 50101), (2, 5010101), (2, 5010102), (2, 601), (2, 602), (2, 603), (2, 604), (2, 605) ON CONFLICT DO NOTHING;
-- 系统管理

























-- 代码生成


-- 通用组件（301 基础 / 302 表单 / 303 表格）



-- 多级菜单 / 路由参数



-- ----------------------------
-- 表结构：sys_user
-- ----------------------------
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(64),
    nickname varchar(64),
    gender smallint DEFAULT 1,
    password varchar(100),
    dept_id bigint,
    avatar varchar(255),
    mobile varchar(20),
    status smallint DEFAULT 1,
    email varchar(128),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_user IS '系统用户表';
COMMENT ON COLUMN sys_user.username IS '用户名';
COMMENT ON COLUMN sys_user.nickname IS '昵称';
COMMENT ON COLUMN sys_user.gender IS '性别((1-男 2-女 0-保密)';
COMMENT ON COLUMN sys_user.password IS '密码';
COMMENT ON COLUMN sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN sys_user.avatar IS '用户头像';
COMMENT ON COLUMN sys_user.mobile IS '联系方式';
COMMENT ON COLUMN sys_user.status IS '状态(1-正常 0-禁用)';
COMMENT ON COLUMN sys_user.email IS '用户邮箱';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';
COMMENT ON COLUMN sys_user.create_by IS '创建人ID';
COMMENT ON COLUMN sys_user.update_time IS '更新时间';
COMMENT ON COLUMN sys_user.update_by IS '修改人ID';
COMMENT ON COLUMN sys_user.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

-- ----------------------------
-- 表数据：sys_user
-- ----------------------------
INSERT INTO sys_user VALUES (1, 'youlai', '有来技术', 0, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', NULL, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345677', 1, 'youlaitech@163.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (2, 'admin', '系统管理员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18888888888', 1, 'youlaitech@163.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (3, 'test', '测试小用户', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345679', 1, 'youlaitech@163.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (4, 'dept_manager', '部门主管', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345680', 1, 'manager@youlaitech.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (5, 'dept_member', '部门成员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345681', 1, 'member@youlaitech.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (6, 'employee', '普通员工', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 2, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345682', 1, 'employee@youlaitech.com', now(), NULL, now(), NULL, 0);
INSERT INTO sys_user VALUES (7, 'custom_user', '自定义权限用户', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345683', 1, 'custom@youlaitech.com', now(), NULL, now(), NULL, 0);

-- ----------------------------
-- 表结构：sys_user_role
-- ----------------------------
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户角色关联表';
COMMENT ON COLUMN sys_user_role.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_role.role_id IS '角色ID';

-- ----------------------------
-- 表数据：sys_user_role
-- ----------------------------
INSERT INTO sys_user_role VALUES (1, 1) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (2, 2) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (3, 3) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (4, 4) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (5, 5) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (6, 6) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role VALUES (7, 7) ON CONFLICT DO NOTHING;

-- ----------------------------
-- 表结构：sys_log
-- ----------------------------
DROP TABLE IF EXISTS sys_log;
CREATE TABLE sys_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    module smallint NOT NULL,
    action_type smallint NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    operator_id BIGINT,
    operator_name VARCHAR(50),
    request_uri VARCHAR(255),
    request_method VARCHAR(10),
    ip VARCHAR(45),
    province VARCHAR(100),
    city VARCHAR(100),
    device VARCHAR(100),
    os VARCHAR(100),
    browser VARCHAR(100),
    status smallint DEFAULT 1,
    error_msg VARCHAR(255),
    execution_time INT,
    create_time timestamp,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_log IS '系统操作日志表';
COMMENT ON COLUMN sys_log.id IS '主键';
COMMENT ON COLUMN sys_log.module IS '模块，数字枚举，参考 LogModule 枚举';
COMMENT ON COLUMN sys_log.action_type IS '操作类型，数字枚举，参考 ActionType 枚举';
COMMENT ON COLUMN sys_log.title IS '前端显示标题';
COMMENT ON COLUMN sys_log.content IS '自定义日志内容';
COMMENT ON COLUMN sys_log.operator_id IS '操作人ID';
COMMENT ON COLUMN sys_log.operator_name IS '操作人名称';
COMMENT ON COLUMN sys_log.request_uri IS '请求路径';
COMMENT ON COLUMN sys_log.request_method IS '请求方法';
COMMENT ON COLUMN sys_log.ip IS 'IP地址';
COMMENT ON COLUMN sys_log.province IS '省份';
COMMENT ON COLUMN sys_log.city IS '城市';
COMMENT ON COLUMN sys_log.device IS '设备';
COMMENT ON COLUMN sys_log.os IS '操作系统';
COMMENT ON COLUMN sys_log.browser IS '浏览器';
COMMENT ON COLUMN sys_log.status IS '0失败 1成功';
COMMENT ON COLUMN sys_log.error_msg IS '错误信息';
COMMENT ON COLUMN sys_log.execution_time IS '执行时间(ms)';
COMMENT ON COLUMN sys_log.create_time IS '操作时间';
CREATE INDEX idx_module_action_time ON sys_log (module, action_type, create_time);
CREATE INDEX idx_operator_time ON sys_log (operator_id, create_time);
CREATE INDEX idx_time ON sys_log (create_time);

-- ----------------------------
-- 表结构：gen_table
-- ----------------------------
DROP TABLE IF EXISTS gen_table;
CREATE TABLE gen_table (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    table_name varchar(100) NOT NULL,
    module_name varchar(100),
    package_name varchar(255) NOT NULL,
    business_name varchar(100) NOT NULL,
    entity_name varchar(100) NOT NULL,
    author varchar(50) NOT NULL,
    parent_menu_id bigint,
    remove_table_prefix varchar(20),
    page_type varchar(20),
    create_time timestamp,
    update_time timestamp,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE gen_table IS '代码生成配置表';
COMMENT ON COLUMN gen_table.table_name IS '表名';
COMMENT ON COLUMN gen_table.module_name IS '模块名';
COMMENT ON COLUMN gen_table.package_name IS '包名';
COMMENT ON COLUMN gen_table.business_name IS '业务名';
COMMENT ON COLUMN gen_table.entity_name IS '实体类名';
COMMENT ON COLUMN gen_table.author IS '作者';
COMMENT ON COLUMN gen_table.parent_menu_id IS '上级菜单ID，对应sys_menu的id ';
COMMENT ON COLUMN gen_table.remove_table_prefix IS '要移除的表前缀，如: sys_';
COMMENT ON COLUMN gen_table.page_type IS '页面类型(classic|crud)';
COMMENT ON COLUMN gen_table.create_time IS '创建时间';
COMMENT ON COLUMN gen_table.update_time IS '更新时间';
COMMENT ON COLUMN gen_table.is_deleted IS '是否删除';
CREATE UNIQUE INDEX uk_tablename ON gen_table (table_name);

-- ----------------------------
-- 表结构：gen_table_column
-- ----------------------------
DROP TABLE IF EXISTS gen_table_column;
CREATE TABLE gen_table_column (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    table_id bigint NOT NULL,
    column_name varchar(100),
    column_type varchar(50),
    column_length int,
    field_name varchar(100) NOT NULL,
    field_type varchar(100),
    field_sort int,
    field_comment varchar(255),
    max_length int,
    is_required smallint,
    is_show_in_list smallint DEFAULT 0,
    is_show_in_form smallint DEFAULT 0,
    is_show_in_query smallint DEFAULT 0,
    query_type smallint,
    form_type smallint,
    dict_type varchar(50),
    create_time timestamp,
    update_time timestamp,
    PRIMARY KEY (id)
);
COMMENT ON TABLE gen_table_column IS '代码生成字段配置表';
COMMENT ON COLUMN gen_table_column.table_id IS '关联的表配置ID';
COMMENT ON COLUMN gen_table_column.field_name IS '字段名称';
COMMENT ON COLUMN gen_table_column.field_type IS '字段类型';
COMMENT ON COLUMN gen_table_column.field_sort IS '字段排序';
COMMENT ON COLUMN gen_table_column.field_comment IS '字段描述';
COMMENT ON COLUMN gen_table_column.is_required IS '是否必填';
COMMENT ON COLUMN gen_table_column.is_show_in_list IS '是否在列表显示';
COMMENT ON COLUMN gen_table_column.is_show_in_form IS '是否在表单显示';
COMMENT ON COLUMN gen_table_column.is_show_in_query IS '是否在查询条件显示';
COMMENT ON COLUMN gen_table_column.query_type IS '查询方式';
COMMENT ON COLUMN gen_table_column.form_type IS '表单类型';
COMMENT ON COLUMN gen_table_column.dict_type IS '字典类型';
COMMENT ON COLUMN gen_table_column.create_time IS '创建时间';
COMMENT ON COLUMN gen_table_column.update_time IS '更新时间';
CREATE INDEX idx_table_id ON gen_table_column (table_id);

-- ----------------------------
-- 系统配置表
-- ----------------------------
DROP TABLE IF EXISTS sys_config;
CREATE TABLE sys_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    config_name varchar(50) NOT NULL,
    config_key varchar(50) NOT NULL,
    config_value varchar(100) NOT NULL,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.config_name IS '配置名称';
COMMENT ON COLUMN sys_config.config_key IS '配置key';
COMMENT ON COLUMN sys_config.config_value IS '配置值';
COMMENT ON COLUMN sys_config.remark IS '备注';
COMMENT ON COLUMN sys_config.create_time IS '创建时间';
COMMENT ON COLUMN sys_config.create_by IS '创建人ID';
COMMENT ON COLUMN sys_config.update_time IS '更新时间';
COMMENT ON COLUMN sys_config.update_by IS '更新人ID';
COMMENT ON COLUMN sys_config.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

INSERT INTO sys_config VALUES (1, '系统限流QPS', 'IP_QPS_THRESHOLD_LIMIT', '10', '单个IP请求的最大每秒查询数（QPS）阈值Key', now(), 1, NULL, NULL, 0);

-- ----------------------------
-- 通知公告表
-- ----------------------------
DROP TABLE IF EXISTS sys_notice;
CREATE TABLE sys_notice (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50),
    content text,
    type smallint NOT NULL,
    level varchar(5) NOT NULL,
    target_type smallint NOT NULL,
    target_user_ids varchar(255),
    publisher_id bigint,
    publish_status smallint DEFAULT 0,
    publish_time timestamp,
    revoke_time timestamp,
    create_by bigint NOT NULL,
    create_time timestamp NOT NULL,
    update_by bigint,
    update_time timestamp,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_notice IS '系统通知公告表';
COMMENT ON COLUMN sys_notice.title IS '通知标题';
COMMENT ON COLUMN sys_notice.content IS '通知内容';
COMMENT ON COLUMN sys_notice.type IS '通知类型（关联字典编码：notice_type）';
COMMENT ON COLUMN sys_notice.level IS '通知等级（字典code：notice_level）';
COMMENT ON COLUMN sys_notice.target_type IS '目标类型（1: 全体, 2: 指定）';
COMMENT ON COLUMN sys_notice.target_user_ids IS '目标人ID集合（多个使用英文逗号,分割）';
COMMENT ON COLUMN sys_notice.publisher_id IS '发布人ID';
COMMENT ON COLUMN sys_notice.publish_status IS '发布状态（0: 未发布, 1: 已发布, -1: 已撤回）';
COMMENT ON COLUMN sys_notice.publish_time IS '发布时间';
COMMENT ON COLUMN sys_notice.revoke_time IS '撤回时间';
COMMENT ON COLUMN sys_notice.create_by IS '创建人ID';
COMMENT ON COLUMN sys_notice.create_time IS '创建时间';
COMMENT ON COLUMN sys_notice.update_by IS '更新人ID';
COMMENT ON COLUMN sys_notice.update_time IS '更新时间';
COMMENT ON COLUMN sys_notice.is_deleted IS '是否删除（0: 未删除, 1: 已删除）';

INSERT INTO sys_notice VALUES (1, 'v3.0.0 版本发布 - 多租户功能上线', '<p>🎉 新版本发布，主要更新内容：</p><p>1. 新增多租户功能，支持租户隔离和数据管理</p><p>2. 优化系统性能，提升响应速度</p><p>3. 完善权限管理，增强安全性</p><p>4. 修复已知问题，提升系统稳定性</p>', 1, 'H', 1, NULL, 1, 1, '2024-12-15 10:00:00', NULL, 1, '2024-12-15 10:00:00', 1, '2024-12-15 10:00:00', 0);
INSERT INTO sys_notice VALUES (2, '系统维护通知 - 2024年12月20日', '<p>⏰ 系统维护通知</p><p>系统将于 <strong>2024年12月20日（本周五）凌晨 2:00-4:00</strong> 进行例行维护升级。</p><p>维护期间系统将暂停服务，请提前做好数据备份工作。</p><p>给您带来的不便，敬请谅解！</p>', 2, 'H', 1, NULL, 1, 1, '2024-12-18 14:30:00', NULL, 1, '2024-12-18 14:30:00', 1, '2024-12-18 14:30:00', 0);
INSERT INTO sys_notice VALUES (3, '安全提醒 - 防范钓鱼邮件', '<p>⚠️ 安全提醒</p><p>近期发现有不法分子通过钓鱼邮件进行网络攻击，请大家提高警惕：</p><p>1. 不要点击来源不明的邮件链接</p><p>2. 不要下载可疑附件</p><p>3. 遇到可疑邮件请及时联系IT部门</p><p>4. 定期修改密码，使用强密码策略</p>', 3, 'H', 1, NULL, 1, 1, '2024-12-10 09:00:00', NULL, 1, '2024-12-10 09:00:00', 1, '2024-12-10 09:00:00', 0);
INSERT INTO sys_notice VALUES (4, '元旦假期安排通知', '<p>📅 元旦假期安排</p><p>根据国家法定节假日安排，公司元旦假期时间为：</p><p><strong>2024年12月30日（周一）至 2025年1月1日（周三）</strong>，共3天。</p><p>2024年12月29日（周日）正常上班。</p><p>祝大家元旦快乐，假期愉快！</p>', 4, 'M', 1, NULL, 1, 1, '2024-12-25 16:00:00', NULL, 1, '2024-12-25 16:00:00', 1, '2024-12-25 16:00:00', 0);
INSERT INTO sys_notice VALUES (5, '新产品发布会邀请', '<p>🎊 新产品发布会邀请</p><p>公司将于 <strong>2025年1月15日下午14:00</strong> 在总部会议室举办新产品发布会。</p><p>届时将展示最新研发的产品和技术成果，欢迎全体员工参加。</p><p>请各部门提前安排好工作，准时参加。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-28 11:00:00', NULL, 1, '2024-12-28 11:00:00', 1, '2024-12-28 11:00:00', 0);
INSERT INTO sys_notice VALUES (6, 'v2.16.1 版本更新', '<p>✨ 版本更新</p><p>v2.16.1 版本已发布，主要修复内容：</p><p>1. 修复 WebSocket 重复连接导致的后台线程阻塞问题</p><p>2. 优化通知公告功能，提升用户体验</p><p>3. 修复部分已知bug</p><p>建议尽快更新到最新版本。</p>', 1, 'M', 1, NULL, 1, 1, '2024-12-05 15:30:00', NULL, 1, '2024-12-05 15:30:00', 1, '2024-12-05 15:30:00', 0);
INSERT INTO sys_notice VALUES (7, '年终总结会议通知', '<p>📋 年终总结会议通知</p><p>各部门年终总结会议将于 <strong>2024年12月30日上午9:00</strong> 召开。</p><p>请各部门负责人提前准备好年度工作总结和下年度工作计划。</p><p>会议地点：总部大会议室</p>', 5, 'M', 2, '1,2', 1, 1, '2024-12-22 10:00:00', NULL, 1, '2024-12-22 10:00:00', 1, '2024-12-22 10:00:00', 0);
INSERT INTO sys_notice VALUES (8, '系统功能优化完成', '<p>✅ 系统功能优化</p><p>已完成以下功能优化：</p><p>1. 优化用户管理界面，提升操作体验</p><p>2. 增强数据导出功能，支持更多格式</p><p>3. 优化搜索功能，提升查询效率</p><p>4. 修复部分界面显示问题</p>', 1, 'L', 1, NULL, 1, 1, '2024-12-12 14:20:00', NULL, 1, '2024-12-12 14:20:00', 1, '2024-12-12 14:20:00', 0);
INSERT INTO sys_notice VALUES (9, '员工培训计划', '<p>📚 员工培训计划</p><p>为提升员工专业技能，公司将于 <strong>2025年1月8日-10日</strong> 组织技术培训。</p><p>培训内容：</p><p>1. 新技术框架应用</p><p>2. 代码规范与最佳实践</p><p>3. 系统架构设计</p><p>请各部门合理安排工作，确保培训顺利进行。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-20 09:30:00', NULL, 1, '2024-12-20 09:30:00', 1, '2024-12-20 09:30:00', 0);
INSERT INTO sys_notice VALUES (10, '数据备份提醒', '<p>💾 数据备份提醒</p><p>请各部门注意定期备份重要数据，建议每周至少备份一次。</p><p>备份方式：</p><p>1. 使用系统自带备份功能</p><p>2. 手动导出重要数据</p><p>3. 联系IT部门协助备份</p><p>数据安全，人人有责！</p>', 3, 'L', 1, NULL, 1, 1, '2024-12-08 08:00:00', NULL, 1, '2024-12-08 08:00:00', 1, '2024-12-08 08:00:00', 0);

-- ----------------------------
-- 用户通知公告表
-- ----------------------------
DROP TABLE IF EXISTS sys_user_notice;
CREATE TABLE sys_user_notice (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    notice_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_read smallint DEFAULT 0,
    read_time timestamp,
    create_time timestamp NOT NULL,
    update_time timestamp,
    is_deleted smallint DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_user_notice IS '用户通知公告关联表';
COMMENT ON COLUMN sys_user_notice.id IS 'id';
COMMENT ON COLUMN sys_user_notice.notice_id IS '公共通知id';
COMMENT ON COLUMN sys_user_notice.user_id IS '用户id';
COMMENT ON COLUMN sys_user_notice.is_read IS '读取状态（0: 未读, 1: 已读）';
COMMENT ON COLUMN sys_user_notice.read_time IS '阅读时间';
COMMENT ON COLUMN sys_user_notice.create_time IS '创建时间';
COMMENT ON COLUMN sys_user_notice.update_time IS '更新时间';
COMMENT ON COLUMN sys_user_notice.is_deleted IS '逻辑删除(0: 未删除, 1: 已删除)';

INSERT INTO sys_user_notice VALUES (1, 1, 2, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (2, 2, 2, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (3, 3, 2, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (4, 4, 2, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (5, 5, 2, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (6, 6, 2, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (7, 7, 2, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (8, 8, 2, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (9, 9, 2, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (10, 10, 2, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (11, 1, 1, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (12, 2, 1, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (13, 3, 1, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (14, 4, 1, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (15, 5, 1, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (16, 6, 1, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (17, 7, 1, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (18, 8, 1, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (19, 9, 1, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (20, 10, 1, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (21, 1, 3, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (22, 2, 3, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (23, 3, 3, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (24, 4, 3, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (25, 5, 3, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (26, 6, 3, 0, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (27, 8, 3, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (28, 9, 3, 1, NULL, now(), now(), 0);
INSERT INTO sys_user_notice VALUES (29, 10, 3, 0, NULL, now(), now(), 0);

-- ----------------------------
-- 表结构：sys_user_social
-- ----------------------------
DROP TABLE IF EXISTS sys_user_social;
CREATE TABLE sys_user_social (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    platform varchar(20) NOT NULL,
    openid varchar(64) NOT NULL,
    unionid varchar(64) DEFAULT NULL,
    nickname varchar(64) DEFAULT NULL,
    avatar varchar(255) DEFAULT NULL,
    session_key varchar(128) DEFAULT NULL,
    verified smallint DEFAULT 1,
    create_time timestamp DEFAULT NULL,
    update_time timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE sys_user_social IS '用户第三方账号绑定表';
COMMENT ON COLUMN sys_user_social.id IS '主键ID';
COMMENT ON COLUMN sys_user_social.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_social.platform IS '平台类型(WECHAT_MINI/WECHAT_MP/ALIPAY/QQ/APPLE)';
COMMENT ON COLUMN sys_user_social.openid IS '平台openid';
COMMENT ON COLUMN sys_user_social.unionid IS '微信unionid';
COMMENT ON COLUMN sys_user_social.nickname IS '第三方昵称';
COMMENT ON COLUMN sys_user_social.avatar IS '第三方头像URL';
COMMENT ON COLUMN sys_user_social.session_key IS '微信session_key';
COMMENT ON COLUMN sys_user_social.verified IS '是否已验证(1-已验证 0-未验证)';
COMMENT ON COLUMN sys_user_social.create_time IS '绑定时间';
COMMENT ON COLUMN sys_user_social.update_time IS '更新时间';
CREATE UNIQUE INDEX uk_platform_openid ON sys_user_social (platform, openid);
CREATE INDEX idx_user_id ON sys_user_social (user_id);
CREATE INDEX idx_unionid ON sys_user_social (unionid);

-- ----------------------------
-- 3. 重置 IDENTITY 序列以匹配已存在的种子数据
-- ----------------------------
-- PostgreSQL 的 GENERATED BY DEFAULT AS IDENTITY 在显式指定 id 插入种子数据时不会自动推进底层序列，
-- 导致首个自增 INSERT 取到已被种子占用的 id，触发主键唯一约束冲突（HTTP 500）。
-- 用各表当前最大 id 重置序列，使下一个自增值为 MAX(id)+1。
SELECT setval(pg_get_serial_sequence('sys_dept', 'id'), COALESCE((SELECT MAX(id) FROM sys_dept), 1));
SELECT setval(pg_get_serial_sequence('sys_dict', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict), 1));
SELECT setval(pg_get_serial_sequence('sys_dict_item', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict_item), 1));
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), COALESCE((SELECT MAX(id) FROM sys_menu), 1));
SELECT setval(pg_get_serial_sequence('sys_role', 'id'), COALESCE((SELECT MAX(id) FROM sys_role), 1));
SELECT setval(pg_get_serial_sequence('sys_user', 'id'), COALESCE((SELECT MAX(id) FROM sys_user), 1));
SELECT setval(pg_get_serial_sequence('sys_log', 'id'), COALESCE((SELECT MAX(id) FROM sys_log), 1));
SELECT setval(pg_get_serial_sequence('gen_table', 'id'), COALESCE((SELECT MAX(id) FROM gen_table), 1));
SELECT setval(pg_get_serial_sequence('gen_table_column', 'id'), COALESCE((SELECT MAX(id) FROM gen_table_column), 1));
SELECT setval(pg_get_serial_sequence('sys_config', 'id'), COALESCE((SELECT MAX(id) FROM sys_config), 1));
SELECT setval(pg_get_serial_sequence('sys_notice', 'id'), COALESCE((SELECT MAX(id) FROM sys_notice), 1));
SELECT setval(pg_get_serial_sequence('sys_user_notice', 'id'), COALESCE((SELECT MAX(id) FROM sys_user_notice), 1));
SELECT setval(pg_get_serial_sequence('sys_user_social', 'id'), COALESCE((SELECT MAX(id) FROM sys_user_social), 1));



